---
kubernetes:
  children:
    master:
      hosts:
        l-kms0:
          ansible_host: 10.211.55.35
    worker:
      hosts:
        l-node-01:
          ansible_host: 10.211.55.36
        l-node-02:
          ansible_host: 10.211.55.37
        l-node-03:
          ansible_host: 10.211.55.39
