---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Australia/Sydney"
  KUBE_VIP_ADDR: "10.211.55.240"
  METALLB_LB_RANGE: "10.211.55.220-10.211.55.230"
  METALLB_K8S_GATEWAY_ADDR: "10.211.55.220"
  METALLB_INGRESS_ADDR: "10.211.55.221"
